version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fica_facil_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
      - ./static:/app/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fica_facil_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    container_name: fica_facil_nginx
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
