# Generated by Django 5.1.1 on 2024-10-02 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=340)),
                ('titular', models.CharField(max_length=250)),
                ('regime', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('data_abertura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Bloqueada', 'Bloqueada'), ('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Finalizada', 'Finalizada')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='Media/Tarefas/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
