# Generated by Django 5.1.1 on 2024-11-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tarefa_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
