# Generated by Django 5.1.1 on 2024-12-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tarefa_cnpj_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
