# Generated by Django 5.1.1 on 2024-12-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tarefa_data_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
